### model
model_name_or_path: Qwen/Qwen2-7B-Instruct
print_param_status: true

### method
stage: sft
do_train: true
finetuning_type: lora
# lora_target: q_proj,v_proj
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
deepspeed: ds/ds_z2_config.json
seed: 123
pissa_init: true

### dataset
dataset_dir: /data/lyx/AI_TCM/hangu_data/data_Alpaca_sft
dataset: data1_Alpaca
template: qwen
cutoff_len: 1024
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/lyx/AI_TCM/AI_LLM/saves/Qwen2-7b/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
ddp_timeout: 180000000
bf16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
