### model
# model_name_or_path: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/outputs/saves/DeepSeek-V2-Lite/full_pt/12-12-05-06-47/checkpoint-60
model_name_or_path: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/outputs/saves/DeepSeek-V2-Lite/full_pt/pzb_5.0e-5_0.2_12-24-13-41-17/checkpoint-300
flash_attn: fa2

### method
stage: sft
do_predict: true
finetuning_type: full

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
# eval_dataset: sft_data_Alpaca_task_1.json, sft_data_Alpaca_task_2.json, sft_data_Alpaca_task_3.json, sft_data_Alpaca_task_4.json, sft_data_Alpaca_task_5.json, sft_data_Alpaca_task_6.json 
# eval_dataset: eval_data
eval_dataset: sft_test_data
template: deepseek
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/DeepSeek-V2-Lite/full_pt/predict/12-12-10-19-18
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
ddp_timeout: 180000000
