
### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
adapter_name_or_path: outputs/saves/Qwen2.5-7B-Instruct/sft/12-09-01-53-42_4.0e-5_0.3
flash_attn: fa2

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
eval_dataset: sft_test_data
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/Qwen2.5-7B-Instruct/predict_sft/12-09-01-53-42_4.0e-5_0.3
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
ddp_timeout: 180000000
