### model
model_name_or_path: outputs/saves/gemma-2-9b-it/full_pt/wzh_5.0e-5_0.25_12-11-02-01-15
# adapter_name_or_path: outputs/saves/gemma-2-9b-it/full_pt/wzh_5.0e-5_0.3_12-10-09-05-00
# flash_attn: fa2

### method
stage: sft
do_predict: true
finetuning_type: full
# deepspeed: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/configs/ds/ds_z3_config.json

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/pt
eval_dataset: sft_test_data
template: gemma
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/gemma-2-9b-it/predict/wzh_5.0e-5_0.25_12-11-02-01-15
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
ddp_timeout: 180000000