### model
model_name_or_path: outputs/saves/Meta-Llama-3-8B-Instruct/full_pt/lsy_5.0e-5_0.2_12-25-00-58-06
# model_name_or_path: outputs/saves/Meta-Llama-3-8B-Instruct/full_pt/12-06-07-53-47_5.0e-5_0.05
# adapter_name_or_path: outputs/saves/Meta-Llama-3-8B-Instruct/lara_pt/12-06-03-00-11
flash_attn: fa2

### method
stage: sft
do_predict: true
finetuning_type: full

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
# eval_dataset: sft_data_Alpaca_task_1.json, sft_data_Alpaca_task_2.json, sft_data_Alpaca_task_3.json, sft_data_Alpaca_task_4.json, sft_data_Alpaca_task_5.json, sft_data_Alpaca_task_6.json 
eval_dataset: sft_test_data
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/Meta-Llama-3-8B-Instruct/predict/lsy_5.0e-5_0.2_12-25-00-58-06
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
ddp_timeout: 180000000
