### model
model_name_or_path: Qwen/Qwen2.5-72B-Instruct
quantization_bit: 4
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]
# adapter_name_or_path: outputs/saves/Qwen2.5-72B-Instruct/sft/cht_5.0e-5_0.3_01-03-03-27-17
flash_attn: fa2

### method
stage: sft
do_predict: true
finetuning_type: lora
# deepspeed: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/configs/ds/ds_z3_config.json

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
# eval_dataset: sft_data_Alpaca_task_1.json, sft_data_Alpaca_task_2.json, sft_data_Alpaca_task_3.json, sft_data_Alpaca_task_4.json, sft_data_Alpaca_task_5.json, sft_data_Alpaca_task_6.json 
eval_dataset: sft_test_data
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/Qwen2.5-72B-Instruct/predict/base
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
max_new_tokens: 256
ddp_timeout: 180000000
