### model
model_name_or_path: outputs/saves/Qwen2.5-7B-Instruct/full_pt/cht_1.0e-5_0.15_12-26-07-44-14
adapter_name_or_path: outputs/saves/Qwen2.5-7B-Instruct/sft/lsy_1.0e-5_0.15_01-03-04-08-01
flash_attn: fa2

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
eval_dataset: sft_test_2
template: qwen
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/Qwen2.5-7B-Instruct/predict_sft/
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
ddp_timeout: 180000000
