### model
model_name_or_path: outputs/saves/Qwen2.5-7B-Instruct/full_pt/cht_5.0e-5_0.1_12-25-00-23-09
flash_attn: fa2

### method
stage: sft
do_predict: true
finetuning_type: full

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/pt
# eval_dataset: sft_data_Alpaca_task_1.json, sft_data_Alpaca_task_2.json, sft_data_Alpaca_task_3.json, sft_data_Alpaca_task_4.json, sft_data_Alpaca_task_5.json, sft_data_Alpaca_task_6.json 
eval_dataset: sft_test_data
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/Qwen2.5-7B-Instruct/predict/cht_5.0e-5_0.1_12-25-00-23-09
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
ddp_timeout: 180000000
