### model
model_name_or_path: outputs/saves/vicuna-7b-v1.5/full_pt/12-12-08-31-24
# adapter_name_or_path: outputs/saves/vicuna-7b-v1.5/sft/12-06-06-52-57
flash_attn: fa2

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
# eval_dataset: sft_data_Alpaca_task_1.json, sft_data_Alpaca_task_2.json, sft_data_Alpaca_task_3.json, sft_data_Alpaca_task_4.json, sft_data_Alpaca_task_5.json, sft_data_Alpaca_task_6.json 
eval_dataset: eval_data
template: llama2
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/vicuna-7b-v1.5/full_pt/predict/12-12-08-31-24
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
ddp_timeout: 180000000
