### model
model_name_or_path: Qwen/Qwen2.5-72B-Instruct
quantization_bit: 4
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
# lora_target: q_proj,v_proj
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
# deepspeed: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/configs/ds/ds_z3_config.json
# deepspeed: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/configs/ds/ds_z3_offload_config.json
seed: 123
# pissa_init: true

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
dataset: sft_train_0
template: qwen
cutoff_len: 2048
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/Qwen2.5-72B-Instruct/sft/12-04-09-02-29
logging_steps: 100
save_steps: 30000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.2
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 150