### model
# model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_name_or_path: outputs/saves/Qwen2.5-7B-Instruct/full_pt/cht_1.0e-5_0.15_12-26-07-44-14
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
# lora_target: q_proj,v_proj
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
# deepspeed: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/configs/ds/ds_z3_config.json
seed: 123
pissa_init: true

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
dataset: ts_train_task_2_doc_1
template: qwen
cutoff_len: 1024
# max_samples: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/Qwen2.5-7B-Instruct/sft/12-09-01-54-38_4.0e-5_0.3
logging_steps: 100
save_steps: 100000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 6
gradient_accumulation_steps: 8
learning_rate: 4.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.3
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500