### model
model_name_or_path: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/outputs/saves/vicuna-7b-v1.5/full_pt/11-20-02-09-51/checkpoint-15000
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: /GLOBALFS/sysu_wangp_1/AITCM/AITCM/datasets/sft
dataset: all_sft_data
template: llama2
cutoff_len: 2048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/saves/vicuna-7b-v1.5/sft/12-06-06-52-57
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true
# lora_target: q_proj,v_proj
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
# deepspeed: ds/ds_z2_config.json
seed: 123
pissa_init: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.35
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000